//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebRole1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iptocountry
    {
        public int Id { get; set; }
        public Nullable<long> ipStart { get; set; }
        public Nullable<long> ipEnd { get; set; }
        public string countryCode { get; set; }
        public string countryName { get; set; }
    }
}
